# https://github.com/andrew8088/dotfiles/blob/main/tmux/tmux.conf
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'fcsonline/tmux-thumbs'

set-environment -g TMUX_PLUGIN_MANAGER_PATH "~/.tmux/tpm-plugins"

# Reload config file
bind r source-file ~/.tmux.conf 

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Spliting
bind v split-window -h
bind h split-window -v

set -g mouse on                  # Enable mouse mode (tmux 2.1 and above)
set -g base-index 1              # start indexing windows at 1 instead of 0
set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g escape-time 0             # zero-out escape time delay
set -g history-limit 1000000     # increase history size (from 2,000)
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard
#set -g status-position top       # macOS / darwin style
setw -g mode-keys vi             # use vi keys in buffer
# set -g allow-rename off        # don't rename windows automatically

# Switch panes using Alt-arrow without prefix. M is for Meta, which is usually your Alt key
bind -n ^ last-window
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# resize panes more easily
bind < resize-pane -L 10
bind > resize-pane -R 10
bind - resize-pane -D 10
bind + resize-pane -U 10

bind o run-shell "tmux neww ~/.local/scripts/tmux-sessionizer"
bind i run-shell "tmux neww ~/.local/scripts/tmux-cht.sh"

set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

set -g @catppuccin_date_time "%Y-%m-%d %H:%M"
set -g @catppuccin_host "on"
set -g @catppuccin_left_separator "█"
set -g @catppuccin_right_separator "█"
set -g @catppuccin_flavor 'mocha'

run '~/.tmux/plugins/tpm/tpm'